# Generated by Django 6.0.5 on 2026-05-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200, verbose_name='Текст')),
                ('url', models.TextField(verbose_name='Адрес url')),
                ('sender', models.CharField(max_length=55, verbose_name='Отправитель')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Данные запроса',
                'verbose_name_plural': 'Данные запросов',
            },
        ),
    ]
