# Generated by Django 6.0.5 on 2026-05-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdata',
            name='sender',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='text',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='url',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес url'),
        ),
    ]
